name: "Carry out checks"

on:
  push:
  pull_request:

jobs:
  type-checking:
    name: "Type checking"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install mypy
      - run: mypy draw_io_parser.py

  linting:
    name: "Linting"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install pylint
      - run: pylint draw_io_parser.py

  formatting:
    name: "Formatting"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install autopep8
      - run: autopep8 --diff --exit-code draw_io_parser.py
