name: "Build"

on:
  push:
    branches:
      - 'main'

jobs:
  build-windows:
    name: "Build (Windows)"
    runs-on: 'windows-latest'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: pip install pyinstaller
      - run: pyinstaller draw_io_parser.py
      # Verify that it works
      - run: ./dist/draw_io_parser/draw_io_parser --help
      - uses: actions/upload-artifact@v4
        with:
          name: "artifact-windows"
          path: dist/*

  build-mac:
    name: "Build (Mac)"
    runs-on: 'macos-latest'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: pip install pyinstaller
      - run: pyinstaller draw_io_parser.py
      # Verify that it works
      - run: ./dist/draw_io_parser/draw_io_parser --help
      - uses: actions/upload-artifact@v4
        with:
          name: "artifact-mac"
          path: dist/*

  build-linux:
    name: "Build (Linux)"
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: pip install pyinstaller
      - run: pyinstaller draw_io_parser.py
      # Verify that it works
      - run: ./dist/draw_io_parser/draw_io_parser --help
      - uses: actions/upload-artifact@v4
        with:
          name: "artifact-linux"
          path: dist/*
